In [ ]:
!pip install sklearn numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2955 sha256=81af2472265cb491fc110fa5cbbcbba7e05ea5408504272ad68282f45bcf7166
  Stored in directory: /root/.cache/pip/wheels/f8/e0/3d/9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn


You are given a dataset of iris flowers. The dataset has four features (sepal length, sepal width, petal length, and petal width) and three possible classes (setosa, versicolor, and virginica). Your task is to implement Maximum Likelihood Classification to predict the class of new flowers.







In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
# Load the data from the file
data = np.load('iris_data.npz')
X_train = data['X_train']
X_test = data['X_test']
y_train = data['y_train']
y_test = data['y_test']

print("X_train", X_train)
print("X_test", X_test)
print("y_train", y_train)
print("y_test",y_test)


X_train [[5.6 3.  4.1 1.3]
 [5.  3.4 1.6 0.4]
 [4.9 3.6 1.4 0.1]
 [6.7 3.3 5.7 2.5]
 [6.4 3.2 5.3 2.3]
 [5.4 3.9 1.3 0.4]
 [4.9 3.  1.4 0.2]
 [5.1 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [7.6 3.  6.6 2.1]
 [5.4 3.9 1.7 0.4]
 [6.7 3.1 5.6 2.4]
 [6.2 3.4 5.4 2.3]
 [7.2 3.  5.8 1.6]
 [5.  3.5 1.3 0.3]
 [6.7 2.5 5.8 1.8]
 [5.6 2.7 4.2 1.3]
 [7.4 2.8 6.1 1.9]
 [6.3 2.8 5.1 1.5]
 [5.  2.3 3.3 1. ]
 [4.6 3.6 1.  0.2]
 [6.1 2.9 4.7 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.1 2.5 3.  1.1]
 [5.  3.3 1.4 0.2]
 [6.3 3.3 4.7 1.6]
 [7.3 2.9 6.3 1.8]
 [6.5 2.8 4.6 1.5]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [6.4 2.8 5.6 2.1]
 [6.3 2.7 4.9 1.8]
 [5.7 2.6 3.5 1. ]
 [5.  3.5 1.6 0.6]
 [4.3 3.  1.1 0.1]
 [5.8 2.7 4.1 1. ]
 [5.5 2.6 4.4 1.2]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.7 1.5]
 [6.9 3.1 5.4 2.1]
 [5.4 3.  4.5 1.5]
 [5.5 2.4 3.7 1. ]
 [5.9 3.  5.1 1.8]
 [6.1 3.  4.9 1.8]
 [5.1 3.8 1.5 0.3]
 [5.2 4.1 1.5 0.1]
 [6.1 3.  4.6 1.4]
 [4.8 3.  1.4 0.1]
 [5.7 2.5 5.  2. ]
 [4.4 3.2 1.3 0.2]
 [5.

Implement Maximum Likelihood Classification

In [ ]:
# Implement a function that takes the mean and variance of a class, and a new sample, and returns the likelihood of the sample belonging to that class
def likelihood(mean, variance, x):
    pass

def likelihood_classify(X_train, y_train, X_test):
  # TODO: Compute the mean and variance of each feature for each class in the training set
  means = []
  variances = []
  
  # TODO: print means and variances

  # TODO: For each new sample in the testing set, compute the likelihood of belonging to each class, and predict the class with the highest likelihood
  # TODO: use previously implemented function
  y_pred = []
  
  return y_pred

# TODO: Compute the accuracy of your classifier on the testing set
# TODO: print accuracy

y_pred = likelihood_classify(X_train, y_train, X_test)

accuracy = None
print(f"Accuracy: {accuracy:.2f}")

Implement Parallelepiped Classification

In [ ]:
def parallelepiped_classifier(train_data, train_labels, test_data):
    # TODO: Calculate the class means and covariances for each class
    class_means = []
    class_covs = []
    
    # Classify the test data based on the Mahalanobis distance from the class means
    y_pred = []
    
    return y_pred

# Apply the Parallelepiped Classifier to the iris dataset
y_pred = parallelepiped_classifier(X_train, y_train, X_test)

# TODO: Calculate the accuracy of the classifier

print(f"Accuracy: {accuracy:.2f}")