## Students Information

Please enter the names and IDs of the four students below:

1. **Name**: Mark Yasser Nabil
   **ID**: `9203106`

2. **Name**: Bemoi Erian Ayad
   **ID**: `9202391`

3. **Name**: Peter Atef Fathi
   **ID**: `9202395`

4. **Name**: Karim Mahmoud Kamal
   **ID**: `9203076`



## Students Instructions

This is your fourth graded lab assignment, as you put the work you have studied in the lectures in action, please take this opportunity to enhance your understanding of the concepts and hone your skills. As you work on your assignment, please keep the following instructions in mind:

- Clearly state your personal information where indicated.
- Be ready with your work before the time of the next discussion slot in the schedule.
- Plagiarism will be met with penalties, refrain from copying any answers to make the most out of the assignment. If any signs of plagiarism are detected, actions will be taken.
- It is acceptable to share the workload of the assignment bearing the discussion in mind.
- Feel free to [reach out](mailto:cmpsy27@gmail.com) if there were any ambiguities or post on the classroom.

## Submission Instructions

To ensure a smooth evaluation process, please follow these steps for submitting your work:

1. **Prepare Your Submission:** Alongside your main notebook, include any additional files that are necessary for running the notebook successfully. This might include data files, images, or supplementary scripts.

2. **Rename Your Files:** Before submission, please rename your notebook to reflect the IDs of the two students working on this project. The format should be `ID1_ID2`, where `ID1` and `ID2` are the student IDs. For example, if the student IDs are `9123456` and `9876543`, then your notebook should be named `9123456_9876543.ipynb`.

3. **Check for Completeness:** Ensure that all required tasks are completed and that the notebook runs from start to finish without errors. This step is crucial for a smooth evaluation.

4. **Submit Your Work:** Once everything is in order, submit your notebook and any additional files via the designated submission link on Google Classroom **(code: 2yj6e24)**. Make sure you meet the submission deadline to avoid any late penalties.
5. Please, note that the same student should submit the assignments for the pair throughout the semester.

By following these instructions carefully, you help us in evaluating your work efficiently and fairly **and any failure to adhere to these guidelines can affect your grades**. If you encounter any difficulties or have questions about the submission process, please reach out as soon as possible.

We look forward to seeing your completed projects and wish you the best of luck!


## Installation Instructions

In this lab assignment, we require additional Python libraries for machine learning (ML) and deep learning (DL) algorithms and frameworks. To fulfill these requirements, we need to install Pytorch.
1. Install Pytorch \
PyTorch is a versatile and powerful machine learning library for Python, known for its flexibility and ease of use in research and production. It supports various deep learning operations and models, including convolutional and recurrent neural networks. For Windows users, the installation also requires ensuring that CUDA, provided by NVIDIA, is compatible to enable GPU acceleration. This enhances performance significantly, particularly in training large neural networks.\
For windows installation with GPU support you can [check out this link](https://pytorch.org/get-started/locally/) which is the source for the command below and please know that support for GPU is done for windows so you can also check out [previous versions](https://pytorch.org/get-started/previous-versions/), you could use CPU on windows smoothly, use linux or resort to [WSL](https://www.youtube.com/watch?v=R4m8YEixidI).

```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```
```bash
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```


> **Note:** You are allowed to install any other necessary libraries you deem useful for solving the lab. Please ensure that any additional libraries are compatible with the project requirements and are properly documented in your submission.


## Convolutional Neural Networks (CNN)

Machine learning is a field of artificial intelligence that enables systems to learn from data and make decisions without being explicitly programmed. It involves algorithms that iteratively learn from data and improve their accuracy over time by optimizing an error metric, typically through the use of loss functions. These functions quantify the difference between the predicted outputs and the actual outputs, guiding the algorithm to minimize this error during training. By continually adjusting and improving, machine learning models can achieve remarkable accuracy in tasks ranging from simple classification to complex decision-making scenarios.

Convolutional Neural Networks (CNNs) are a specialized kind of neural networks particularly effective for analyzing visual imagery. They employ a mathematical operation known as convolution, which uses sliding window techniques to process data. This method is highly efficient in recognizing patterns and features in images due to the sparse interactions and parameter sharing of convolutional layers. These characteristics allow CNNs to capture local patterns like edges and textures with a significantly reduced amount of parameters compared to fully connected networks, making them highly efficient for tasks involving high-dimensional data like images.

### Key Components of CNN Architecture

The architecture of a Convolutional Neural Network (CNN) typically includes several key components, each playing a crucial role in the network's ability to process and interpret visual information:

- **Convolutional Layers**:
  - Apply a number of filters to the input.
  - Create feature maps that capture essential details within the data.

- **Pooling Layers**:
  - Often follow convolutional layers.
  - Reduce the spatial size of the feature maps, decreasing the computational load.
  - Extract dominant features that are invariant to small changes in the input.

- **Fully Connected Layers**:
  - Interpret the features extracted by convolutional and pooling layers.
  - Perform classification or regression tasks based on the interpreted features.

- **Softmax Layer**:
  - Typically used in the final layer if the task is classification.
  - Outputs the probabilities of the instance belonging to each class.

- **Dropout Layers**:
  - Included to prevent overfitting.
  - Randomly drop units from the neural network during the training process to improve generalization.



### Example of CNN Architecture: LeNet-5

![Example: LeNet-5 Architecture](lenet5.png)

### Overview of Neural Network Hyperparameters

In training neural networks, various hyperparameters must be predefined to guide the training process. These include:

- **Batch Size**
  - **Definition**: Number of training examples used per iteration.
  - **Common Values**: 32, 64, 128, 256.

- **Learning Rate**
  - **Definition**: Step size at each iteration to minimize the loss function.
  - **Common Values**: Often starts small, e.g., 0.01, 0.001, and can be dynamically adjusted (lowered as we get nearer to minima, check scheduers).

- **Optimizer Type**
  - **Examples**: SGD (Stochastic Gradient Descent), Adam, RMSprop, Adagrad.
  - **Role**: Different optimizers affect training dynamics and model performance differently.

- **Beta Parameters for Adam Optimizer**
  - **Beta1 and Beta2**: Control the decay rates of moving averages of past gradients and squared gradients.
  - **Common Values**: Beta1 = 0.9, Beta2 = 0.999.

- **Epochs**
  - **Definition**: One full pass of the training dataset through the learning algorithm.
  - **Usage**: More epochs can lead to better learning but risk overfitting.

- **Momentum**
  - **Definition**: Helps accelerate SGD and dampens oscillations.
  - **Common Values**: 0.9, 0.99.

- **Regularization Parameters (L1 & L2)**
  - **Purpose**: Prevent overfitting by adding a penalty on the size of the coefficients.
  - **Parameters**: Lambda or alpha values for L1 (Lasso) and L2 (Ridge) regularization.

- **Dropout Rate**
  - **Definition**: Fraction of neurons to randomly drop during training.
  - **Common Values**: 0.2, 0.3, 0.5.

- **Number of Layers and Number of Neurons in Each Layer**
  - **Role**: Determines the architecture's depth and width, affecting its ability to capture complex patterns.

- **Error Function Type for Classification with Softmax**
  - **Definition**: Cross-entropy loss, also known as log loss.
  - **Purpose**: Measures the performance of a classification model whose output is a probability value between 0 and 1. Cross-entropy loss increases as the predicted probability diverges from the actual label (an alternative can be Categorical Hinge Loss).

- **Early Stopping**
  - **Purpose**: Halt training when performance on a validation set starts to worsen to prevent overfitting.

Each of these hyperparameters can significantly impact the effectiveness and efficiency of the neural network training process, and tuning them appropriately is crucial for achieving optimal performance.


## Req- Image Classification for EuroSATallBands
This is the same problem of the previous lab but we will explore the power of machine learning. Image classification in remote sensing is not as popular as pixel classification but we will get to that later.

- **Load the Images**: Load the images of the EuroSAT dataset that belong to the **residential**, **river**, and **forest** classes.

- **Split the Dataset**: Split the dataset such that 10% of each class is used as validation data and other 10% is used as testing data, and the remainder is used for training your classifier. Use the indices provided by `np.random.choice` with seed set to `27`. **Code is provided do not change it**.

- **CNN Architecture**: Use or implement one of the popular suitable CNN architectures, even with pretrained weights if you like.

- **Hyperparameters Tuning**: According to your validation accuaracy, you should make altercations to your architectures and hyperparameters, you can even change the architecture altogether, the loss function, optimizer or others.

- **Report Accuracy and Average F1 Score**: After testing your classifier on the test set, report the **Accuracy** and **Average F1 Score** of your model.


In [36]:
# Add your libraries here
import numpy as np
import cv2
from sklearn.metrics import confusion_matrix, f1_score


import torch
import torch.nn as nn
from torchvision import transforms
import torch.optim as optim
from torch.utils.data import Dataset, random_split
from torchsummary import summary

In [37]:
##The dataset is loaded to your GDrive so need to be mounted
from google.colab import drive
import os
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/Colab Notebooks/Satellite Labs/Lab 4 - Convolutional Neural Networks')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:
# DO NOT CHANGE THIS CELL
## Training set indices.
np.random.seed(27)  # Set random seed for reproducibility

# Randomly select indices for the test sets for each class
residential_indices = np.random.choice(np.arange(3000), size=600, replace=False)
forest_indices = np.random.choice(np.arange(3000), size=600, replace=False)
river_indices = np.random.choice(np.arange(2500), size=500, replace=False)

residential_val_indices = residential_indices[:300]
forest_val_indices = forest_indices[:300]
river_val_indices = river_indices[:250]

residential_test_indices = residential_indices[300:]
forest_test_indices = forest_indices[300:]
river_test_indices = river_indices[250:]

In [39]:
class LeNet5(nn.Module):
    def __init__(self, nums=3):
        super(LeNet5, self).__init__()
        self.nums = nums
        # CNN layers
        self.conv = nn.Sequential(
            # Conv1, 5x5, s=1
            nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=1, padding=0),
            nn.ReLU(),
            # nn.Sigmoid(),
            # avg pool, f=2, s=2
            nn.MaxPool2d(kernel_size=2, stride=2),
            # Conv2, 5x5, s=1
            nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5, stride=1, padding=0),
            nn.ReLU(),
            # nn.Sigmoid(),
            # avg pool, f=2, s=2
            nn.MaxPool2d(kernel_size=2, stride=2),
        )
        # Feed forward NN layers
        self.fc = nn.Sequential(
            nn.Linear(in_features=5 * 5 * 16, out_features=120),
            # nn.Sigmoid(),
            nn.ReLU(),
            # nn.Dropout(0.2),
            nn.Linear(in_features=120, out_features=84),
            # nn.Sigmoid(),
            nn.ReLU(),
            nn.Linear(in_features=84, out_features=self.nums),
            # nn.ReLU(),
        )

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

In [40]:
class CustomDataset(Dataset):
    def __init__(self, data_path, transform=None, classes=[], load_type="train", test_indices=None):
        self.data_path = data_path
        self.transform = transform
        self.classes = classes
        self.class_to_idx = {cls: idx for idx, cls in enumerate(self.classes)}
        self.load_type = load_type
        self.test_indices = test_indices
        self.image_extension = 'jpg' if 'RGB' in self.data_path else 'tif'
        self.images = self._load_images()


    def _load_images(self):
        images = []
        for class_name in self.classes:
            class_path = os.path.join(self.data_path, class_name)
            class_images_path = os.listdir(class_path)
            class_images_length = len(class_images_path)
            # class_images_length = 10
            if self.load_type == "train":
                print(f"Reading {class_images_length - len(self.test_indices[class_name])} training images in Class: {class_name}")
            if self.load_type == "test":
                print(f"Reading {len(self.test_indices[class_name])} testing images in Class: {class_name}")

            for i in range(1, class_images_length + 1):
                if self.load_type == "train" and (i-1) in self.test_indices[class_name]:
                    continue
                if self.load_type == "test" and (i-1) not in self.test_indices[class_name]:
                    continue
                image_name = f"{class_name}_{i}.{self.image_extension}"
                image_path = os.path.join(class_path, image_name)
                # =====================================================
                # =================READ AND PREPROCESS=================
                # =====================================================

                # Read the image
                image = cv2.imread(image_path)

                # Resize the image to 32x32
                image = cv2.resize(image, (32, 32))

                # Convert the image to float32
                image = image.astype('float32')

                # Normalize the pixel values to the range [0, 1]
                image /= 255.0

                # Convert to RGB
                # image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

                # Transpose the image: H x W x C -> C x H x W
                image = image.transpose(2, 0, 1)

                image = torch.tensor(image)

                if self.transform:
                    image = self.transform(image)
                    # print(image)

                label = self.class_to_idx[class_name]
                label =  torch.tensor(label)
                # print(label)
                images.append((image,label))
        return images

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image, label = self.images[idx]
        return image, label

In [41]:
# Define transforms to preprocess the images (e.g., normalization)
# transform = transforms.Compose([
#     transforms.ToTensor(),
# ])
transform = None
# Define the path to your dataset folder
rgb_base_path = "./data/EuroSAT-RGB/2750"
band_base_path = "./data/EuroSATallBands/ds/images/remote_sensing/otherDatasets/sentinel_2/tif/"
data_path = rgb_base_path
classes = ['Residential', 'River', 'Forest']
test_indices = {
    'Residential': residential_test_indices,
    'Forest': forest_test_indices,
    'River': river_test_indices
}
# Use CustomDataset to load your dataset
full_train_dataset = CustomDataset(data_path, transform=transform, classes=classes, load_type="train", test_indices=test_indices)

# Use CustomDataset to load your dataset
test_dataset = CustomDataset(data_path, transform=transform, classes=classes, load_type="test", test_indices=test_indices)

# Define the sizes for train and validation sets
train_size = int(0.8 * len(full_train_dataset))  # 80% for training
val_size = len(full_train_dataset) - train_size  # Remaining for validation

# Split the dataset into train and validation sets
train_dataset, val_dataset = random_split(full_train_dataset, [train_size, val_size])
print(f"Train size: {train_size}, Validation size: {val_size}")

Reading 2700 training images in Class: Residential
Reading 2250 training images in Class: River
Reading 2700 training images in Class: Forest
Reading 300 testing images in Class: Residential
Reading 250 testing images in Class: River
Reading 300 testing images in Class: Forest
Train size: 6120, Validation size: 1530


In [42]:
# Define batch size
batch_size = 512
# Create a DataLoader to iterate over the dataset in batches during training
full_train_loader = torch.utils.data.DataLoader(full_train_dataset, batch_size=batch_size)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)
test_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size)

In [43]:
# Define LeNet5 model
model = LeNet5(nums=len(classes))
# Move the model to CUDA if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")
model.to(device)

Device: cuda


LeNet5(
  (conv): Sequential(
    (0): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
    (4): ReLU()
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Sequential(
    (0): Linear(in_features=400, out_features=120, bias=True)
    (1): ReLU()
    (2): Linear(in_features=120, out_features=84, bias=True)
    (3): ReLU()
    (4): Linear(in_features=84, out_features=3, bias=True)
  )
)

In [44]:
summary(model,(3,32,32))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1            [-1, 6, 28, 28]             456
              ReLU-2            [-1, 6, 28, 28]               0
         MaxPool2d-3            [-1, 6, 14, 14]               0
            Conv2d-4           [-1, 16, 10, 10]           2,416
              ReLU-5           [-1, 16, 10, 10]               0
         MaxPool2d-6             [-1, 16, 5, 5]               0
            Linear-7                  [-1, 120]          48,120
              ReLU-8                  [-1, 120]               0
            Linear-9                   [-1, 84]          10,164
             ReLU-10                   [-1, 84]               0
           Linear-11                    [-1, 3]             255
Total params: 61,411
Trainable params: 61,411
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.01
Forward/ba

# Model Training and Evaluation

In [57]:
def train_model(model, loader, device, num_epochs,learning_rate, print_eps=True):
    # Define loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    # optimizer = optim.SGD(model.parameters(), lr=learning_rate)
    optimizer = optim.Adam(model.parameters(), lr=learning_rate, betas=(0.9, 0.999))
    # Set the model to training mode
    model.train()

    # Training loop
    for epoch in range(num_epochs):
        running_loss = 0.0
        for images, labels in loader:
            # Move input data to the CUDA if available
            images, labels = images.to(device), labels.to(device)
            # print(images)

            # Zero the gradients
            optimizer.zero_grad()

            # Forward pass
            outputs = model(images)

            # Compute loss
            loss = criterion(outputs, labels)

            # Backward pass
            loss.backward()

            # Update parameters
            optimizer.step()

            # Accumulate the loss for printing
            running_loss += loss.item()

        # Print average loss for each epoch
        if print_eps:
          print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}")
    return model

def evaluate_model(model, loader, device):
    # Set the model to evaluation mode
    model.eval()

    correct = 0
    total = 0
    all_labels = []
    all_predictions = []

    # We don't need gradients for evaluation, so wrap in
    # no_grad to save memory
    with torch.no_grad():
        for images, labels in loader:
            # Move input data to the CUDA if available
            images, labels = images.to(device), labels.to(device)

            # Forward pass
            outputs = model(images)

            # Get prediction from the maximum value
            _, predicted = torch.max(outputs.data, 1)

            # Total number of labels
            total += labels.size(0)

            # Total correct predictions
            correct += (predicted == labels).sum().item()

            # Store labels and predictions for confusion matrix
            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predicted.cpu().numpy())

    accuracy = correct / total * 100
    print(f'Accuracy: {accuracy} %')
    # Calculate F1 score for each class
    f1_scores = f1_score(all_labels, all_predictions, average=None)

    # Calculate average F1 score
    avg_f1 = np.mean(f1_scores)
    print(f'Average F1 score: {avg_f1}')

    # Calculate confusion matrix
    conf_matrix = confusion_matrix(all_labels, all_predictions)
    print('Confusion Matrix:')
    print(conf_matrix)


    return accuracy, avg_f1, conf_matrix

# Hyperparameter Tuning

In [68]:
# Define a range of hyperparameters to explore
learning_rates = [0.01, 0.001, 0.0001, 0.00001]
num_epochs_list = [160, 120, 80]


best_accuracy = 0.0
best_hyperparams = {}

# Iterate over hyperparameters combinations
for lr in learning_rates:
    for num_epochs in num_epochs_list:
        # Define LeNet5 model
        model = LeNet5(nums=len(classes))
        model.to(device)

        model = train_model(model, full_train_loader, device, num_epochs, lr,  print_eps=False)

        # Print validation accuracy for the current hyperparameters
        print(f"======================================================================")
        print(f"Validation Accuracy with lr={lr}, num_epochs={num_epochs}")
        print(f"======================================================================")
        # Evaluate the model on the validation set
        accuracy, _, _ = evaluate_model(model, val_loader, device)


        # Update the best hyperparameters if the current model performs better
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_hyperparams['learning_rate'] = lr
            best_hyperparams['num_epochs'] = num_epochs

# Print the best hyperparameters
print(f"Best hyperparameters: {best_hyperparams}, Best accuracy: {best_accuracy}")

Validation Accuracy with lr=0.01, num_epochs=160
Accuracy: 33.59477124183007 %
Average F1 score: 0.16764514024788
Confusion Matrix:
[[  0   0 549]
 [  0   0 467]
 [  0   0 514]]
Validation Accuracy with lr=0.01, num_epochs=120
Accuracy: 33.59477124183007 %
Average F1 score: 0.16764514024788
Confusion Matrix:
[[  0   0 549]
 [  0   0 467]
 [  0   0 514]]
Validation Accuracy with lr=0.01, num_epochs=80
Accuracy: 33.59477124183007 %
Average F1 score: 0.16764514024788
Confusion Matrix:
[[  0   0 549]
 [  0   0 467]
 [  0   0 514]]
Validation Accuracy with lr=0.001, num_epochs=160
Accuracy: 92.81045751633987 %
Average F1 score: 0.9256749650444056
Confusion Matrix:
[[525  24   0]
 [ 25 400  42]
 [  5  14 495]]
Validation Accuracy with lr=0.001, num_epochs=120
Accuracy: 93.13725490196079 %
Average F1 score: 0.929413576347411
Confusion Matrix:
[[525  24   0]
 [ 23 410  34]
 [  5  19 490]]
Validation Accuracy with lr=0.001, num_epochs=80
Accuracy: 92.61437908496733 %
Average F1 score: 0.9239682

# Train using best parameters on full training set (training+validation)

In [69]:
# Define training parameters
learning_rate = best_hyperparams['learning_rate']
num_epochs = best_hyperparams['num_epochs']
# Define LeNet5 model
model = LeNet5(nums=len(classes))
model.to(device)

model = train_model(model, full_train_loader, device, num_epochs,learning_rate)
# save the model
torch.save(model.state_dict(), 'lenet_model.pth')

Epoch [1/120], Loss: 1.4113
Epoch [2/120], Loss: 1.3796
Epoch [3/120], Loss: 1.3775
Epoch [4/120], Loss: 1.3761
Epoch [5/120], Loss: 1.3896
Epoch [6/120], Loss: 1.3710
Epoch [7/120], Loss: 1.3746
Epoch [8/120], Loss: 1.3728
Epoch [9/120], Loss: 1.3688
Epoch [10/120], Loss: 1.3670
Epoch [11/120], Loss: 1.3439
Epoch [12/120], Loss: 1.3280
Epoch [13/120], Loss: 1.2916
Epoch [14/120], Loss: 1.2377
Epoch [15/120], Loss: 1.2514
Epoch [16/120], Loss: 1.1557
Epoch [17/120], Loss: 1.0909
Epoch [18/120], Loss: 0.8768
Epoch [19/120], Loss: 0.9801
Epoch [20/120], Loss: 1.0987
Epoch [21/120], Loss: 0.8208
Epoch [22/120], Loss: 0.7682
Epoch [23/120], Loss: 0.7818
Epoch [24/120], Loss: 0.7377
Epoch [25/120], Loss: 0.7560
Epoch [26/120], Loss: 0.7361
Epoch [27/120], Loss: 1.0030
Epoch [28/120], Loss: 1.1143
Epoch [29/120], Loss: 0.7623
Epoch [30/120], Loss: 0.7772
Epoch [31/120], Loss: 0.6851
Epoch [32/120], Loss: 0.7430
Epoch [33/120], Loss: 0.6543
Epoch [34/120], Loss: 0.6339
Epoch [35/120], Loss: 0

# Testing on testing set

In [70]:
accuracy, avg_f1, conf_matrix = evaluate_model(model, test_loader, device)

Accuracy: 92.61437908496733 %
Average F1 score: 0.9233026729352853
Confusion Matrix:
[[2017  130    4]
 [  99 1564  120]
 [  20   79 2087]]


### Grading Rubric (Total: 10 Marks)

The lab is graded based on the following criteria:

1. **Data Loading and Preparation (2 Marks)**
   - Correctly loads images for the residential, river, and forest classes. (1 Mark)
   - Accurately splits the dataset into training, validation testing subsets and clearly shows this split. (1 Mark)

2. **CNN Architecture (3 Marks)**
   - Uses appropriate CNN Architecture to the problem with a full pipeline. (2 Marks)
   - Justifies the selection of CNN architecture. (1 Mark)

3. **Hyperparameters Tuning (2 Marks)**
   - Report evaluation metrics on validation set. (1 Mark)
   - Analyzes results and tunes hyperparameters. (1 Mark)

4. **Model Evaluation and Understanding (3 Marks)**
   - Shows **confusion matrix** and correctly calculates and clearly shows the calculations for Accuracy and Average F1 Score. (1 Mark)
   - **Comparison amongst your peers.** Compares the model's performance against those of peers to identify strengths and areas for improvement. (2 Marks)

Each section of the lab will be evaluated on completeness, and correctness in approach and analysis. Part of the rubric also includes the student's ability to explain and justify their choices and results.
